### ISSUE TITLE
REGDB_E_CLASSNOTREG when consuming the WinUI package

### ISSUE THREAD

**Issue by softworkz** [ffmpeginteropx/FFmpegInteropX#376]
This is similar to the case with UWP when the native files are not in the `/runtimes/xxx/native` folders. The WinRT components don't get registered properly:

```
Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Private.CoreLib.dll
Exception thrown: 'System.TypeInitializationException' in FFmpegInteropX.DotNet.dll
Failed to create playback item for http://xxxx/master.m3u8 System.TypeInitializationException: The type initializer for 'WinRT.ActivationFactory`1' threw an exception.
 ---> System.Runtime.InteropServices.COMException (0x80040154): Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
   at WinRT.ActivationFactory`1..ctor()
   at WinRT.ActivationFactory`1..cctor()
   --- End of inner exception stack trace ---
   at WinRT.ActivationFactory`1.As(Guid iid)
   at FFmpegInteropX.FFmpegMediaSource.Make___objRef_global__FFmpegInteropX_IFFmpegMediaSourceStatics()
   at FFmpegInteropX.FFmpegMediaSource.get__objRef_global__FFmpegInteropX_IFFmpegMediaSourceStatics()
   at FFmpegInteropX.FFmpegMediaSource.CreateFromUriAsync(String uri)
   at Emby.WinInteropPlayer.Features.TransportControl.WinTransportControllerVideo.Play(StartPlaybackOptions options)
Async event fires PlayerWinVideoerror
>>>> Warn WinVideoPlayer.ReportError: The type initializer for 'WinRT.ActivationFactory`1' threw an exception.
```

After adding these two references:

```xml
      <PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.0.3" />
      <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.756" />
```

The output slightly changed:

```
Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Private.CoreLib.dll
Exception thrown: 'System.TypeInitializationException' in FFmpegInteropX.DotNet.dll
Failed to create playback item for http://xxx/master.m3u8: System.TypeInitializationException: The type initializer for 'WinRT.ActivationFactory`1' threw an exception.
 ---> System.Runtime.InteropServices.COMException (0x80040154): Element not found.

   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
   at WinRT.ActivationFactory`1..ctor()
   at WinRT.ActivationFactory`1..cctor()
   --- End of inner exception stack trace ---
   at WinRT.ActivationFactory`1.As(Guid iid)
   at FFmpegInteropX.FFmpegMediaSource.Make___objRef_global__FFmpegInteropX_IFFmpegMediaSourceStatics()
   at FFmpegInteropX.FFmpegMediaSource.get__objRef_global__FFmpegInteropX_IFFmpegMediaSourceStatics()
   at FFmpegInteropX.FFmpegMediaSource.CreateFromUriAsync(String uri)
>>>> Warn WinVideoPlayer.ReportError: The type initializer for 'WinRT.ActivationFactory`1' threw an exception.

```

What's the key to get this working in a WinUI3 project?  (actually it's MAUI)
Any ideas how I can get this set up correctly?

**Comment by softworkz** [comment]
As it turned out, the problem is lying elsewhere. The WinRT registration wasn't the issue. It was about missing MSVC runtime files.

Adding this reference fixed it:

```xml
<PackageReference Include="Microsoft.VCRTForwarders.140" Version="1.0.7" />
```

Even though they say that this shouldn't be needed for a packaged app, which is what it runs as - even in the debugger AFAIU.
Maybe it's a MAUI specific issue.
